import { BTZPluginState } from './types';

export const PRO_STYLE_PRESETS: { id: string; label: string; state: Partial<BTZPluginState> }[] = [
  { id: 'default', label: 'Default', state: { sparkEnabled: true, sparkLUFS: -5, sparkCeiling: -0.3, sparkMix: 1 } },
  { id: 'dynamic-design',   label: 'Dynamic-Design',   state: { transientAmount: .5 } },
  { id: 'punch-smack',      label: 'Punch-Smack',      state: { punch: .8 } },
  { id: 'precision-q',      label: 'Precision-Q',      state: { eqEnabled: true, eqMidGain: 2, eqMidFreq: 2500, eqMidQ: 1.2 } },
  { id: 'analog-reel',      label: 'Analog-Reel',      state: { warmth: .6, drive: .35 } },
  { id: 'vintage-tape',     label: 'Vintage-Tape',     state: { warmth: .8, texture: true } },
  { id: 'sonic-vital',      label: 'Sonic-Vital',      state: { warmth: .4, shineEnabled: true, shineGainDb: 2 } },
  { id: 'classic-76',       label: 'Classic-76',       state: { dynEnabled: true, dynRatio: 8, dynAttack: 1, dynRelease: 80 } },
  { id: 'saturation-decap', label: 'Saturation-Decap', state: { drive: .7 } },
  { id: 'drum-sculpt',      label: 'Drum-Sculpt',      state: { boom: .7, punch: .7 } },
  { id: 'transient-neutron',label: 'Transient-Neutron',state: { transEnabled: true, transAttack: 40, transSustain: -10 } },
  { id: 'bass-synth',       label: 'Bass-Synth',       state: { subEnabled: true, subAmount: 50, subFreq: 45 } },
  { id: 'clarity-air',      label: 'Clarity-Air',      state: { shineEnabled: true, shineGainDb: 4, shineFreqHz: 22000 } },
  { id: 'split-physic',     label: 'Split-Physic',     state: { mix: .8, drive: .3 } },
  { id: 'retro-goeq',       label: 'Retro-GoEQ',       state: { eqEnabled: true, eqLowGain: 1.5, eqHighGain: 2 } },
  { id: 'intelligent-eq',   label: 'Intelligent-EQ',   state: { aiAutomation: true } },
  { id: 'tone-char',        label: 'Tone-Char',        state: { warmth: .5, drive: .3 } },
  { id: 'tube-cascade',     label: 'Tube-Cascade',     state: { clippingType: 'tube', drive: .5 } },
  { id: 'low-mint',         label: 'Low-Mint',         state: { eqEnabled: true, eqLowGain: 3, eqLowFreq: 70 } },
  { id: 'stereo-vital',     label: 'Stereo-Vital',     state: { consoleEnabled: true, consoleCrosstalk: .2 } },
  { id: 'vintage-76',       label: 'Vintage-76',       state: { dynEnabled: true, dynRatio: 12 } },
  { id: 'dynamic-intense',  label: 'Dynamic-Intense',  state: { punch: .8, dynEnabled: true, dynRatio: 6 } },
  { id: 'harmonic-spark',   label: 'Harmonic-Spark',   state: { drive: .6, shineEnabled: true, shineGainDb: 1.5 } },
  { id: 'multiband-saturn', label: 'Multiband-Saturn', state: { drive: .5, warmth: .4 } },
  { id: 'mix-vault',        label: 'Mix-Vault',        state: { masterEnabled: true, masterBlend: 'transparent', masterMacro: .4 } },
  { id: 'drum-trigger',     label: 'Drum-Trigger',     state: { transEnabled: true, transAttack: 60, transSustain: 10 } },
];
