/*
  Box Tone Zone (BTZ) — BTZComponents.h  v1
  ────────────────────────────────────────────────────────────────────────
  Custom JUCE components for the v4 UI overhaul:
    • HarmonicVisualizer — real-time harmonic overtone waterfall display
    • GlassPanel — frosted glass container with backdrop simulation
    • TooltipOverlay — cursor-following parameter value display
    • SimpleKnob — large, tactile knob for Simple Mode
    • DirectManipSpectrum — click-to-control spectrum display
    • StartupReveal — brief brand animation on plugin open
    • MeterStrip — 60fps level meter with peak hold
    • ProcessingIndicator — breathing glow for active modules
  ────────────────────────────────────────────────────────────────────────
  All components are self-contained, resolution-independent, and use
  BTZTheme tokens exclusively for visual constants.
*/
#pragma once

#include <JuceHeader.h>
#include "BTZTheme.h"
#include "BTZDsp.h"
#include <array>
#include <atomic>
#include <cmath>

namespace BTZComponents {

// ═══════════════════════════════════════════════════════════════════════════
// HarmonicVisualizer — the signature "Tone Zone" display
// Shows harmonic overtones generated by saturation in real-time
// ═══════════════════════════════════════════════════════════════════════════
class HarmonicVisualizer : public juce::Component, private juce::Timer {
public:
    HarmonicVisualizer() {
        setOpaque(false);
        startTimerHz(BTZTokens::Animation::harmonicFps);
        for (auto& v : harmonicLevels) v = 0.0f;
        for (auto& v : smoothedLevels) v = 0.0f;
        for (auto& v : ghostLevels)    v = 0.0f;
    }

    void setHarmonicData(const float* levels, int count) {
        int n = juce::jmin(count, kMaxHarmonics);
        for (int i = 0; i < n; ++i)
            harmonicLevels[i] = levels[i];
        for (int i = n; i < kMaxHarmonics; ++i)
            harmonicLevels[i] = 0.0f;
    }

    void setGhostData(const float* levels, int count) {
        int n = juce::jmin(count, kMaxHarmonics);
        for (int i = 0; i < n; ++i)
            ghostLevels[i] = levels[i];
    }

    void setSaturationModel(int modelIndex) { currentModel = modelIndex; }
    void setDriveAmount(float drive01) { driveAmount = drive01; }

    void paint(juce::Graphics& g) override {
        auto bounds = getLocalBounds().toFloat();
        float w = bounds.getWidth();
        float h = bounds.getHeight();

        // Background: subtle dark inset
        g.setColour(juce::Colour(0xFF0E0E14));
        g.fillRoundedRectangle(bounds, BTZTokens::Radius::sm);

        // Glass overlay border
        g.setColour(BTZColours::glassBorder);
        g.drawRoundedRectangle(bounds.reduced(0.5f), BTZTokens::Radius::sm, 0.5f);

        // Draw ghost (before) harmonics
        float barWidth = (float)BTZTokens::Dim::harmonicBarWidth;
        float barGap = (float)BTZTokens::Dim::harmonicBarGap;
        float totalBarWidth = barWidth + barGap;
        int numBars = juce::jmin(kMaxHarmonics, (int)(w / totalBarWidth));
        float startX = (w - numBars * totalBarWidth + barGap) * 0.5f;

        // Ghost bars (input spectrum, faded)
        for (int i = 0; i < numBars; ++i) {
            float level = ghostLevels[i];
            if (level < 0.001f) continue;
            float barH = level * (h - 20.0f);
            float x = startX + i * totalBarWidth;
            float y = h - 10.0f - barH;
            g.setColour(BTZColours::harmonicColour(i).withAlpha(BTZTokens::Opacity::ghostTrace));
            g.fillRoundedRectangle(x, y, barWidth, barH, 2.0f);
        }

        // Active harmonic bars with glow
        for (int i = 0; i < numBars; ++i) {
            float level = smoothedLevels[i];
            if (level < 0.001f) continue;
            float barH = level * (h - 20.0f);
            float x = startX + i * totalBarWidth;
            float y = h - 10.0f - barH;

            juce::Colour barCol = BTZColours::harmonicColour(i);

            // Glow behind bar
            g.setColour(barCol.withAlpha(0.15f * level));
            g.fillRoundedRectangle(x - 2.0f, y - 2.0f, barWidth + 4.0f, barH + 4.0f, 3.0f);

            // Main bar with gradient
            juce::ColourGradient barGrad(
                barCol.brighter(0.3f), x, y,
                barCol.darker(0.2f), x, y + barH, false
            );
            g.setGradientFill(barGrad);
            g.fillRoundedRectangle(x, y, barWidth, barH, 2.0f);

            // Top cap highlight
            g.setColour(barCol.brighter(0.5f));
            g.fillRoundedRectangle(x, y, barWidth, 2.0f, 1.0f);
        }

        // Harmonic number labels
        g.setFont(BTZTheme::Font::micro());
        g.setColour(BTZColours::mute);
        for (int i = 0; i < numBars; ++i) {
            float x = startX + i * totalBarWidth;
            g.drawText(juce::String(i + 1), (int)x, (int)(h - 10.0f), (int)barWidth, 10,
                       juce::Justification::centred, false);
        }

        // Model indicator text
        static const char* modelNames[] = {
            "TANH", "TUBE", "TAPE", "TRANSISTOR", "TRANSFORMER",
            "NEURAL NEVE", "NEURAL API", "NEURAL SSL", "NEURAL CUSTOM",
            "WDF TUBE", "WDF XFMR"
        };
        int idx = juce::jlimit(0, 10, currentModel);
        g.setFont(BTZTheme::Font::label());
        g.setColour(BTZColours::bone.withAlpha(0.6f));
        g.drawText(modelNames[idx], bounds.reduced(8.0f, 4.0f),
                   juce::Justification::topRight, false);

        // Drive amount indicator (subtle arc at bottom)
        if (driveAmount > 0.01f) {
            float arcY = h - 4.0f;
            float arcW = w * driveAmount * 0.8f;
            g.setColour(BTZColours::amber.withAlpha(0.4f * driveAmount));
            g.fillRoundedRectangle((w - arcW) * 0.5f, arcY, arcW, 2.0f, 1.0f);
        }
    }

private:
    static constexpr int kMaxHarmonics = 16;
    std::array<float, kMaxHarmonics> harmonicLevels;
    std::array<float, kMaxHarmonics> smoothedLevels;
    std::array<float, kMaxHarmonics> ghostLevels;
    int currentModel = 0;
    float driveAmount = 0.0f;

    void timerCallback() override {
        // Smooth towards target with exponential decay
        constexpr float attack = 0.3f;
        constexpr float release = 0.08f;
        bool needsRepaint = false;
        for (int i = 0; i < kMaxHarmonics; ++i) {
            float target = harmonicLevels[i];
            float coeff = (target > smoothedLevels[i]) ? attack : release;
            float prev = smoothedLevels[i];
            smoothedLevels[i] += (target - smoothedLevels[i]) * coeff;
            if (std::abs(smoothedLevels[i] - prev) > 0.001f)
                needsRepaint = true;
        }
        if (needsRepaint) repaint();
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(HarmonicVisualizer)
};

// ═══════════════════════════════════════════════════════════════════════════
// GlassPanel — frosted glass container component
// ═══════════════════════════════════════════════════════════════════════════
class GlassPanel : public juce::Component {
public:
    GlassPanel() { setOpaque(false); }

    void setCornerRadius(float r) { radius = r; }
    void setTitle(const juce::String& t) { title = t; repaint(); }

    void paint(juce::Graphics& g) override {
        auto bounds = getLocalBounds().toFloat().reduced(1.0f);
        BTZTheme::drawGlassPanel(g, bounds, radius);

        if (title.isNotEmpty()) {
            g.setFont(BTZTheme::Font::sectionHeader());
            g.setColour(BTZColours::bone);
            g.drawText(title, bounds.reduced(12.0f, 8.0f).removeFromTop(20.0f),
                       juce::Justification::topLeft, false);
        }
    }

    void resized() override {
        // Children get the inner area (inset from glass border)
        auto inner = getLocalBounds().reduced(12, title.isEmpty() ? 12 : 32);
        for (auto* child : getChildren())
            if (child != nullptr)
                child->setBounds(inner);
    }

private:
    float radius = BTZTokens::Radius::md;
    juce::String title;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(GlassPanel)
};

// ═══════════════════════════════════════════════════════════════════════════
// TooltipOverlay — cursor-following parameter value tooltip
// ═══════════════════════════════════════════════════════════════════════════
class TooltipOverlay : public juce::Component, private juce::Timer {
public:
    TooltipOverlay() {
        setOpaque(false);
        setInterceptsMouseClicks(false, false);
        setAlwaysOnTop(true);
    }

    void showValue(const juce::String& paramName, const juce::String& value,
                   juce::Point<int> position) {
        currentName = paramName;
        currentValue = value;
        tipPosition = position;
        opacity = 1.0f;
        setVisible(true);
        startTimerHz(60);
        repaint();
    }

    void fadeOut() { fading = true; }

    void paint(juce::Graphics& g) override {
        if (opacity < 0.01f) return;

        auto tipBounds = juce::Rectangle<float>(
            (float)tipPosition.x + 12.0f, (float)tipPosition.y - 28.0f, 120.0f, 36.0f
        );

        // Clamp to component bounds
        if (tipBounds.getRight() > getWidth())
            tipBounds.setX(getWidth() - tipBounds.getWidth() - 4.0f);
        if (tipBounds.getY() < 0)
            tipBounds.setY((float)tipPosition.y + 16.0f);

        g.setOpacity(opacity);

        // Glass tooltip background
        g.setColour(juce::Colour(0xE0181A22));
        g.fillRoundedRectangle(tipBounds, 4.0f);
        g.setColour(BTZColours::glassBorder);
        g.drawRoundedRectangle(tipBounds, 4.0f, 0.5f);

        // Name
        g.setFont(BTZTheme::Font::label());
        g.setColour(BTZColours::mute);
        g.drawText(currentName, tipBounds.reduced(6.0f, 2.0f).removeFromTop(14.0f),
                   juce::Justification::centredLeft, false);

        // Value
        g.setFont(BTZTheme::Font::value());
        g.setColour(BTZColours::cream);
        g.drawText(currentValue, tipBounds.reduced(6.0f, 2.0f).removeFromBottom(16.0f),
                   juce::Justification::centredLeft, false);
    }

private:
    juce::String currentName, currentValue;
    juce::Point<int> tipPosition;
    float opacity = 0.0f;
    bool fading = false;

    void timerCallback() override {
        if (fading) {
            opacity -= 0.1f;
            if (opacity <= 0.0f) {
                opacity = 0.0f;
                fading = false;
                setVisible(false);
                stopTimer();
            }
            repaint();
        }
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(TooltipOverlay)
};

// ═══════════════════════════════════════════════════════════════════════════
// SimpleKnob — large, tactile knob for Simple Mode with enhanced visuals
// ═══════════════════════════════════════════════════════════════════════════
class SimpleKnob : public juce::Slider {
public:
    SimpleKnob(const juce::String& paramLabel, juce::Colour accent = BTZColours::amber)
        : accentColour(accent), label(paramLabel)
    {
        setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);
        setTextBoxStyle(juce::Slider::NoTextBox, true, 0, 0);
        setRotaryParameters(BTZTheme::KnobStyle::startAngle * juce::MathConstants<float>::pi,
                            BTZTheme::KnobStyle::endAngle * juce::MathConstants<float>::pi, true);
    }

    void paint(juce::Graphics& g) override {
        auto bounds = getLocalBounds().toFloat();
        float size = juce::jmin(bounds.getWidth(), bounds.getHeight());
        auto centre = bounds.getCentre();
        float radius = size * 0.42f;
        float bodyRadius = radius * BTZTheme::KnobStyle::bodyRadiusRatio;

        float normValue = (float)valueToProportionOfLength(getValue());
        float angle = BTZTheme::KnobStyle::startAngle * juce::MathConstants<float>::pi
                    + normValue * (BTZTheme::KnobStyle::endAngle - BTZTheme::KnobStyle::startAngle)
                    * juce::MathConstants<float>::pi;

        // Hover/active glow
        if (isMouseOver() || isMouseButtonDown()) {
            float glowAlpha = isMouseButtonDown() ? BTZColours::activeGlowAlpha : BTZColours::hoverGlowAlpha;
            g.setColour(accentColour.withAlpha(glowAlpha));
            g.fillEllipse(centre.x - radius - 8, centre.y - radius - 8,
                          (radius + 8) * 2, (radius + 8) * 2);
        }

        // Arc track (background)
        juce::Path trackArc;
        trackArc.addCentredArc(centre.x, centre.y, radius, radius, 0.0f,
                               BTZTheme::KnobStyle::startAngle * juce::MathConstants<float>::pi,
                               BTZTheme::KnobStyle::endAngle * juce::MathConstants<float>::pi, true);
        g.setColour(BTZColours::stone);
        g.strokePath(trackArc, juce::PathStrokeType(4.0f, juce::PathStrokeType::curved,
                                                     juce::PathStrokeType::rounded));

        // Arc track (value)
        if (normValue > 0.001f) {
            juce::Path valueArc;
            valueArc.addCentredArc(centre.x, centre.y, radius, radius, 0.0f,
                                   BTZTheme::KnobStyle::startAngle * juce::MathConstants<float>::pi,
                                   angle, true);
            g.setColour(accentColour);
            g.strokePath(valueArc, juce::PathStrokeType(4.0f, juce::PathStrokeType::curved,
                                                         juce::PathStrokeType::rounded));
        }

        // Knob body with 3D convexity
        juce::ColourGradient bodyGrad(
            BTZColours::knobRimLight, centre.x, centre.y - bodyRadius * 0.6f,
            BTZColours::knobShadow, centre.x, centre.y + bodyRadius * 0.8f, false
        );
        bodyGrad.addColour(0.4, BTZColours::knobHighlight);
        bodyGrad.addColour(0.7, BTZColours::knobMid);
        g.setGradientFill(bodyGrad);
        g.fillEllipse(centre.x - bodyRadius, centre.y - bodyRadius,
                      bodyRadius * 2, bodyRadius * 2);

        // Inner shadow for depth
        juce::ColourGradient innerShadow(
            juce::Colours::transparentBlack, centre.x, centre.y,
            juce::Colour(0x30000000), centre.x, centre.y + bodyRadius, true
        );
        g.setGradientFill(innerShadow);
        g.fillEllipse(centre.x - bodyRadius, centre.y - bodyRadius,
                      bodyRadius * 2, bodyRadius * 2);

        // Indicator line
        float indStart = bodyRadius * BTZTheme::KnobStyle::indicatorStart;
        float indEnd = bodyRadius * BTZTheme::KnobStyle::indicatorEnd;
        float ix1 = centre.x + std::sin(angle) * indStart;
        float iy1 = centre.y - std::cos(angle) * indStart;
        float ix2 = centre.x + std::sin(angle) * indEnd;
        float iy2 = centre.y - std::cos(angle) * indEnd;
        g.setColour(accentColour);
        g.drawLine(ix1, iy1, ix2, iy2, 3.0f);

        // Label below
        g.setFont(BTZTheme::Font::simpleLabel());
        g.setColour(BTZColours::cream);
        g.drawText(label, bounds.removeFromBottom(24.0f), juce::Justification::centred, false);

        // Value display
        g.setFont(BTZTheme::Font::simpleValue());
        g.setColour(accentColour);
        juce::String valText = juce::String(getValue(), 1);
        g.drawText(valText, centre.x - 30, centre.y - 8, 60, 16,
                   juce::Justification::centred, false);
    }

private:
    juce::Colour accentColour;
    juce::String label;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(SimpleKnob)
};

// ═══════════════════════════════════════════════════════════════════════════
// ProcessingIndicator — breathing glow for active modules
// ═══════════════════════════════════════════════════════════════════════════
class ProcessingIndicator : public juce::Component, private juce::Timer {
public:
    ProcessingIndicator(juce::Colour col = BTZColours::amber) : colour(col) {
        setOpaque(false);
        startTimerHz(30);
    }

    void setActive(bool active) { isActive = active; }

    void paint(juce::Graphics& g) override {
        if (!isActive) return;
        auto bounds = getLocalBounds().toFloat();
        float alpha = 0.3f + 0.2f * std::sin(phase);
        g.setColour(colour.withAlpha(alpha));
        g.fillEllipse(bounds.reduced(2.0f));
        // Bright core
        g.setColour(colour.withAlpha(alpha * 1.5f));
        g.fillEllipse(bounds.reduced(bounds.getWidth() * 0.25f));
    }

private:
    juce::Colour colour;
    bool isActive = false;
    float phase = 0.0f;

    void timerCallback() override {
        phase += 0.08f;
        if (phase > juce::MathConstants<float>::twoPi) phase -= juce::MathConstants<float>::twoPi;
        if (isActive) repaint();
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(ProcessingIndicator)
};

// ═══════════════════════════════════════════════════════════════════════════
// StartupReveal — brief brand animation when plugin opens
// ═══════════════════════════════════════════════════════════════════════════
class StartupReveal : public juce::Component, private juce::Timer {
public:
    StartupReveal() {
        setOpaque(false);
        setAlwaysOnTop(true);
    }

    void trigger() {
        phase = 0.0f;
        setVisible(true);
        startTimerHz(60);
    }

    void paint(juce::Graphics& g) override {
        auto bounds = getLocalBounds().toFloat();

        // Fade background
        float bgAlpha = juce::jmax(0.0f, 1.0f - phase * 2.0f);
        g.setColour(BTZColours::obsidian.withAlpha(bgAlpha));
        g.fillRect(bounds);

        // Brand text with scale animation
        float scale = 0.8f + phase * 0.2f;
        float textAlpha = (phase < 0.5f) ? phase * 2.0f : juce::jmax(0.0f, 2.0f - phase * 2.0f);

        g.setOpacity(textAlpha);
        auto transform = juce::AffineTransform::scale(scale, scale, bounds.getCentreX(), bounds.getCentreY());
        g.addTransform(transform);

        // "BTZ" in display font
        g.setFont(juce::Font(BTZTokens::Font::display, BTZTokens::Font::Size::size2xl, juce::Font::bold));
        g.setColour(BTZColours::amber);
        g.drawText("BTZ", bounds, juce::Justification::centred, false);

        // Subtitle
        g.setFont(BTZTheme::Font::subtitle());
        g.setColour(BTZColours::bone.withAlpha(textAlpha * 0.7f));
        g.drawText("BOX TONE ZONE", bounds.translated(0, 40), juce::Justification::centred, false);
    }

private:
    float phase = 0.0f;

    void timerCallback() override {
        phase += 0.025f;  // ~600ms total
        if (phase >= 1.0f) {
            setVisible(false);
            stopTimer();
        }
        repaint();
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(StartupReveal)
};

// ═══════════════════════════════════════════════════════════════════════════
// DirectManipSpectrum — click-to-control spectrum display
// Allows direct manipulation of multiband crossover points and per-band gain
// ═══════════════════════════════════════════════════════════════════════════
class DirectManipSpectrum : public juce::Component {
public:
    struct BandInfo {
        float freqHz = 1000.0f;
        float gainDb = 0.0f;
        juce::Colour colour = BTZColours::amber;
        bool active = true;
    };

    DirectManipSpectrum() { setOpaque(false); }

    void setSpectrumData(const float* magnitudes, int numBins, float sampleRate) {
        specData.resize(numBins);
        for (int i = 0; i < numBins; ++i)
            specData[i] = magnitudes[i];
        sr = sampleRate;
        repaint();
    }

    void setBands(const std::vector<BandInfo>& bands) { bandInfos = bands; repaint(); }

    std::function<void(int bandIndex, float newFreqHz)> onCrossoverDrag;
    std::function<void(int bandIndex, float newGainDb)> onGainDrag;

    void paint(juce::Graphics& g) override {
        auto bounds = getLocalBounds().toFloat();

        // Background
        g.setColour(juce::Colour(0xFF0E0E14));
        g.fillRoundedRectangle(bounds, BTZTokens::Radius::sm);

        // Spectrum curve
        if (!specData.empty()) {
            juce::Path specPath;
            float w = bounds.getWidth();
            float h = bounds.getHeight();
            bool started = false;

            for (int i = 0; i < (int)specData.size(); ++i) {
                float freq = (float)i * sr / (float)(specData.size() * 2);
                if (freq < 20.0f || freq > 20000.0f) continue;
                float x = bounds.getX() + freqToX(freq, w);
                float dbVal = 20.0f * std::log10(specData[i] + 1e-10f);
                float y = bounds.getBottom() - ((dbVal + 80.0f) / 80.0f) * h;
                y = juce::jlimit(bounds.getY(), bounds.getBottom(), y);
                if (!started) { specPath.startNewSubPath(x, y); started = true; }
                else specPath.lineTo(x, y);
            }

            // Fill under curve
            if (started) {
                juce::Path fillPath = specPath;
                fillPath.lineTo(bounds.getRight(), bounds.getBottom());
                fillPath.lineTo(bounds.getX(), bounds.getBottom());
                fillPath.closeSubPath();
                g.setColour(BTZColours::amber.withAlpha(0.08f));
                g.fillPath(fillPath);

                g.setColour(BTZColours::amber.withAlpha(0.5f));
                g.strokePath(specPath, juce::PathStrokeType(1.0f));
            }
        }

        // Band crossover lines
        float w = bounds.getWidth();
        for (int i = 0; i < (int)bandInfos.size(); ++i) {
            float x = bounds.getX() + freqToX(bandInfos[i].freqHz, w);
            g.setColour(bandInfos[i].colour.withAlpha(0.6f));
            g.drawVerticalLine((int)x, bounds.getY(), bounds.getBottom());

            // Draggable handle
            g.setColour(bandInfos[i].colour);
            g.fillEllipse(x - 4, bounds.getCentreY() - 4, 8, 8);
        }

        // Border
        g.setColour(BTZColours::glassBorder);
        g.drawRoundedRectangle(bounds.reduced(0.5f), BTZTokens::Radius::sm, 0.5f);
    }

    void mouseDown(const juce::MouseEvent& e) override {
        dragBandIndex = findNearestBand(e.position.x);
    }

    void mouseDrag(const juce::MouseEvent& e) override {
        if (dragBandIndex >= 0 && onCrossoverDrag) {
            float freq = xToFreq(e.position.x - getLocalBounds().toFloat().getX(),
                                 getLocalBounds().toFloat().getWidth());
            onCrossoverDrag(dragBandIndex, freq);
        }
    }

    void mouseUp(const juce::MouseEvent&) override { dragBandIndex = -1; }

private:
    std::vector<float> specData;
    std::vector<BandInfo> bandInfos;
    float sr = 44100.0f;
    int dragBandIndex = -1;

    float freqToX(float freq, float width) const {
        return std::log2(freq / 20.0f) / std::log2(20000.0f / 20.0f) * width;
    }

    float xToFreq(float x, float width) const {
        float norm = x / width;
        return 20.0f * std::pow(2.0f, norm * std::log2(20000.0f / 20.0f));
    }

    int findNearestBand(float mouseX) const {
        float w = (float)getWidth();
        int nearest = -1;
        float minDist = 20.0f;  // pixel threshold
        for (int i = 0; i < (int)bandInfos.size(); ++i) {
            float bx = freqToX(bandInfos[i].freqHz, w);
            float dist = std::abs(mouseX - bx);
            if (dist < minDist) { minDist = dist; nearest = i; }
        }
        return nearest;
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(DirectManipSpectrum)
};

// ═══════════════════════════════════════════════════════════════════════════
// GainReductionRibbon — flowing ribbon showing compression over time
// ═══════════════════════════════════════════════════════════════════════════
class GainReductionRibbon : public juce::Component, private juce::Timer {
public:
    GainReductionRibbon() {
        setOpaque(false);
        startTimerHz(30);
        history.fill(0.0f);
    }

    void pushGR(float grDb) {
        history[writePos] = grDb;
        writePos = (writePos + 1) % kHistorySize;
    }

    void paint(juce::Graphics& g) override {
        auto bounds = getLocalBounds().toFloat();
        float w = bounds.getWidth();
        float h = bounds.getHeight();

        // Background
        g.setColour(juce::Colour(0xFF0E0E14));
        g.fillRoundedRectangle(bounds, BTZTokens::Radius::sm);

        // GR ribbon path
        juce::Path ribbon;
        ribbon.startNewSubPath(bounds.getX(), bounds.getCentreY());

        for (int i = 0; i < kHistorySize; ++i) {
            int idx = (writePos + i) % kHistorySize;
            float x = bounds.getX() + (float)i / (float)kHistorySize * w;
            float grNorm = juce::jlimit(0.0f, 1.0f, -history[idx] / 20.0f);
            float y = bounds.getCentreY() + grNorm * (h * 0.4f);
            ribbon.lineTo(x, y);
        }

        // Mirror for ribbon effect
        juce::Path ribbonTop;
        ribbonTop.startNewSubPath(bounds.getX(), bounds.getCentreY());
        for (int i = 0; i < kHistorySize; ++i) {
            int idx = (writePos + i) % kHistorySize;
            float x = bounds.getX() + (float)i / (float)kHistorySize * w;
            float grNorm = juce::jlimit(0.0f, 1.0f, -history[idx] / 20.0f);
            float y = bounds.getCentreY() - grNorm * (h * 0.35f);
            ribbonTop.lineTo(x, y);
        }

        // Fill between paths
        juce::Path fillArea = ribbon;
        for (int i = kHistorySize - 1; i >= 0; --i) {
            int idx = (writePos + i) % kHistorySize;
            float x = bounds.getX() + (float)i / (float)kHistorySize * w;
            float grNorm = juce::jlimit(0.0f, 1.0f, -history[idx] / 20.0f);
            float y = bounds.getCentreY() - grNorm * (h * 0.35f);
            fillArea.lineTo(x, y);
        }
        fillArea.closeSubPath();

        g.setColour(BTZColours::amber.withAlpha(0.15f));
        g.fillPath(fillArea);
        g.setColour(BTZColours::amber.withAlpha(0.6f));
        g.strokePath(ribbon, juce::PathStrokeType(1.5f));
        g.setColour(BTZColours::amberDim.withAlpha(0.4f));
        g.strokePath(ribbonTop, juce::PathStrokeType(1.0f));

        // Border
        g.setColour(BTZColours::glassBorder);
        g.drawRoundedRectangle(bounds.reduced(0.5f), BTZTokens::Radius::sm, 0.5f);
    }

private:
    static constexpr int kHistorySize = 256;
    std::array<float, kHistorySize> history;
    int writePos = 0;

    void timerCallback() override { repaint(); }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(GainReductionRibbon)
};

} // namespace BTZComponents
